version: 2

jobs:

  build:
    docker:
      - image: circleci/php:7.2-stretch
    steps:
      - run: sudo apt update && sudo docker-php-ext-install zip
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-
      - run: composer install --no-interaction --prefer-dist --no-suggest
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - run:
          name: Build index page
          command: php -f ./build.php
      - run:
          name: Commit changes
          command: |
            git config user.email "${CIRCLE_USERNAME}@gmail.com"
            git config user.name "CircleCI"
            changes=$(git status --short ./docs/index.html);
            if [ -n "$changes" ]; then
              git commit ./docs/index.html -m "Build ${CIRCLE_BUILD_NUM}"
              git push https://${GITHUB_ACCESS_TOKEN}:x-oauth-basic@${CIRCLE_REPOSITORY_URL} ${CIRCLE_BRANCH}
            fi

workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "58 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: datvance-credentials
